name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer:v2

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Install NPM Dependencies
        run: npm install && npm run build

      - name: Set Permissions for Laravel
        run: chmod -R 777 storage bootstrap/cache

      - name: Clear Laravel Cache & Config
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Setup .env File
        run: |
          cat <<EOF > .env
          APP_ENV=local
          APP_DEBUG=true
          APP_URL=http://127.0.0.1:8000
          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=Inventory_Management_System
          DB_USERNAME=root
          DB_PASSWORD=Admin@2025!?
          EOF

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql
          sleep 10  # Give MySQL time to start

      - name: Verify MySQL Service
        run: sudo systemctl status mysql || true

      - name: Verify Database Connection
        env:
          MYSQL_PWD: Admin@2025!?
        run: |
          mysql -u root -e "SHOW DATABASES;"

      - name: Apply .env Configurations
        run: php artisan config:clear && php artisan config:cache

      - name: Run Migrations & Seed Database
        env:
          MYSQL_PWD: Admin@2025!?
        run: php artisan migrate --force --seed

      - name: Run Laravel Tests
        run: php artisan test || true  # Run tests but don't fail deployment

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Replace this with your actual deployment process
          # ssh user@server "cd /var/www/html && git pull origin main && php artisan optimize"
