name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Admin@2025!?
          MYSQL_DATABASE: latest_db
          MYSQL_USER: root
          MYSQL_PASSWORD: Admin@2025!?
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, exif, pcntl, bcmath, gd, pdo_mysql

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo 'Waiting for MySQL...'
            sleep 2
          done

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: latest_db
          DB_USERNAME: root
          DB_PASSWORD: Admin@2025!?
        run: php artisan migrate --force

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: latest_db
          DB_USERNAME: root
          DB_PASSWORD: Admin@2025!?
        run: php artisan test
