name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Change based on your PHP version
          extensions: mbstring, xml, ctype, json, bcmath, zip, pdo_mysql
          coverage: none

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -u root -e "CREATE DATABASE IF NOT EXISTS laravel_db;"
          mysql -u root -e "CREATE USER 'laravel_user'@'localhost' IDENTIFIED BY 'securepassword';"
          mysql -u root -e "GRANT ALL PRIVILEGES ON laravel_db.* TO 'laravel_user'@'localhost';"
          mysql -u root -e "FLUSH PRIVILEGES;"

      - name: Install Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Copy and Configure .env File
        run: |
          cp .env.example .env
          echo "APP_KEY=$(php artisan key:generate --show)" >> .env
          echo "APP_ENV=production" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel_db" >> .env
          echo "DB_USERNAME=laravel_user" >> .env
          echo "DB_PASSWORD=securepassword" >> .env

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Cache Config & Routes
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Setup Supervisor (Queue Worker)
        run: |
          sudo apt-get install supervisor -y
          echo "[program:laravel-worker]
          process_name=%(program_name)s_%(process_num)02d
          command=php /var/www/html/artisan queue:work --tries=3
          autostart=true
          autorestart=true
          numprocs=1
          redirect_stderr=true
          stdout_logfile=/var/log/laravel-worker.log" | sudo tee /etc/supervisor/conf.d/laravel-worker.conf
          sudo supervisorctl reread
          sudo supervisorctl update
          sudo supervisorctl start laravel-worker:*

      - name: Restart Server
        run: sudo systemctl restart nginx php8.1-fpm

      - name: Deploy Completed
        run: echo "🚀 Deployment Successful!"
