name: Deploy PHP Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Run Composer Diagnose
        run: composer diagnose

      - name: Verify PHP Version
        run: php -v

      - name: Set Permissions for Laravel
        run: chmod -R 777 storage bootstrap/cache

      - name: Clear Laravel Cache
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Check Database Connectivity
        run: |
          DB_HOST=$(grep DB_HOST .env | cut -d '=' -f2)
          DB_PORT=$(grep DB_PORT .env | cut -d '=' -f2)
          echo "Checking connectivity to database at $DB_HOST:$DB_PORT"
          nc -zv $DB_HOST $DB_PORT || exit 1

      - name: Run Database Migrations
        run: php artisan migrate --force

      - name: Run Application Tests (Optional)
        run: php artisan test || true  # Run tests but don't fail deployment

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here (e.g., rsync, SSH, etc.)
