name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, json, bcmath, zip, pdo_mysql

      - name: Install Dependencies
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Set Permissions
        run: |
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache

      - name: Configure Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "APP_ENV=production" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=inv-manag-system.chwgc60cgqfa.eu-north-1.rds.amazonaws.com" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=inv-manag-system" >> .env
          echo "DB_USERNAME=admin" >> .env
          echo "DB_PASSWORD=admin1234" >> .env

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Restart Apache
        run: sudo systemctl restart apache2

      - name: Deployment Complete
        run: echo "🚀 Deployment Successful!"
