name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up PHP (Upgrade to 8.2)
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, exif, pcntl, bcmath, gd, pdo_mysql
          coverage: none

      - name: Install Dependencies (Force Update)
        run: |
          composer update --no-interaction
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Database Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate --force

      - name: Clear Cache and Optimize
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy Application
        run: |
          php artisan storage:link
          php artisan optimize
