name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo mysqladmin ping

      - name: Debug MySQL Connection
        run: |
          sudo mysql -e "SELECT user, host FROM mysql.user;"
          sudo mysql -e "SHOW DATABASES;"

      - name: Force Reset MySQL Root Password
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Admin@2025!?';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Verify MySQL Access
        run: |
          export MYSQL_PWD='Admin@2025!?'
          mysql -u root -e "SHOW DATABASES;"
