name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up PHP (Upgrade to 8.2)
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, exif, pcntl, bcmath, gd, pdo_mysql
          coverage: none

      - name: Install Dependencies (Force Update)
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Environment File
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" > .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Wait for Database Connection
        run: |
          echo "Waiting for database connection..."
          for i in {1..30}; do
            nc -z -v -w5 ${{ secrets.DB_HOST }} ${{ secrets.DB_PORT }} && break
            echo "Database not ready, retrying in 5 seconds..."
            sleep 5
          done

      - name: Run Database Migrations
        run: php artisan migrate --force

      - name: Clear Cache and Optimize
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy Application
        run: |
          php artisan storage:link
          php artisan optimize
